# Generated by Django 5.1.15 on 2026-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Site logo (SVG or PNG)', upload_to='logo/'),
        ),
    ]
